### ISSUE TITLE
Readme.md ADO.Net Trace

### ISSUE THREAD

**Issue by itoleck** [lowleveldesign/diagnostics-tools#2]
I believe that mofcomp adonet should be mofcomp adonetdiag.mof

**Comment by lowleveldesign** [comment]
Hi, which file you are referring to? In the ado.net-debugging.md I see the `mofcomp adonetdiag.mof` command.

**Comment by lowleveldesign** [comment]
Sorry, obviously I'm still sleeping. I thought this issue was in my other repo (debug-recipes) 😅 I fixed the README.md file. Great thanks for spotting this!
