### ISSUE TITLE
Web blog out of date - bad links.

### ISSUE THREAD

**Issue by mdell-seradex** [lowleveldesign/diagnostics-tools#3]
Your wordpress web blog [Diagnosing ADO.NET with ETW traces](https://lowleveldesign.wordpress.com/2012/09/07/diagnosing-ado-net-with-etw-traces/) still has links that point to codeplex which was shut down last year.
Just thought I should let you know.

It doesn't seem to want to let me post on that site.

**Comment by lowleveldesign** [comment]
Thanks, I updated the links.
