### ISSUE TITLE
Diagnosing ADO.NET with ETW traces - `logman query providers` command fails

### ISSUE THREAD

**Issue by mdell-seradex** [lowleveldesign/diagnostics-tools#4]
Your wordpress web blog [Diagnosing ADO.NET with ETW traces](https://lowleveldesign.wordpress.com/2012/09/07/diagnosing-ado-net-with-etw-traces/) says to use the following command to check one of the providers: `logman query providers '{914ABDE2-171E-C600-3348-C514171DE148}'`, but when I try that I get 
```
Error:
Element not found.
```
If I execute it without the quotes, it works.  Note that I am one Windows 10 Version 22H2.

**Comment by lowleveldesign** [comment]
I'm using PowerShell in the blog post (notice PS> prompt) and you need to add apostrophes to make this command work. As you noticed, they are not required in cmd.exe.

**Comment by mdell-seradex** [comment]
I did not realize, partially because it says `PS reader>` and partially because I don't use PowerShell often. Too much overhead and it changes or complicates the commands I'm used to.

**Comment by mdell-seradex** [comment]
Do you have any thoughts as to why I can't get it to work?  The last comment on that page is mine. I was finally able to post one.

**Comment by lowleveldesign** [comment]
Try running process monitor and verify that the BidInterface registry key is getting accessed and the DLL is loaded into the .NET process.

**Comment by mdell-seradex** [comment]
OMFG. I could swear I tested this with a non-environment variable path, but today ProcMon showed me that it didn't understand it. I even used ProcMon before. 
Perhaps I changed it after the app was running and it somehow cached the previous version..
I was simply doing what the MS article says. https://learn.microsoft.com/en-us/previous-versions/sql/sql-server-2008/cc765421(v=sql.100)#:~#:text=ADO.NET%202.0-,Value%3D%22%25SYSTEMROOT%25
The download, still available for SQL 2012, has the same setup. Ugh.
It would be great if you could mention this.

Note that I will test this again. Also, the PerfView tool is great for this, if setup correctly...
